# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'config.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Configuration(object):
    def setupUi(self, Configuration):
        Configuration.setObjectName("Configuration")
        Configuration.resize(399, 136)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Configuration.sizePolicy().hasHeightForWidth())
        Configuration.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(Configuration)
        self.verticalLayout.setObjectName("verticalLayout")
        self.audio = QtWidgets.QWidget(Configuration)
        self.audio.setObjectName("audio")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.audio)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.audio)
        self.label.setMinimumSize(QtCore.QSize(128, 0))
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.audioCombo = QtWidgets.QComboBox(self.audio)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.audioCombo.sizePolicy().hasHeightForWidth())
        self.audioCombo.setSizePolicy(sizePolicy)
        self.audioCombo.setObjectName("audioCombo")
        self.horizontalLayout.addWidget(self.audioCombo)
        self.verticalLayout.addWidget(self.audio)
        self.hotkey = QtWidgets.QWidget(Configuration)
        self.hotkey.setObjectName("hotkey")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.hotkey)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.hotkey)
        self.label_2.setMinimumSize(QtCore.QSize(128, 0))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.hotkeyCombo = QtWidgets.QComboBox(self.hotkey)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hotkeyCombo.sizePolicy().hasHeightForWidth())
        self.hotkeyCombo.setSizePolicy(sizePolicy)
        self.hotkeyCombo.setObjectName("hotkeyCombo")
        self.horizontalLayout_2.addWidget(self.hotkeyCombo)
        self.verticalLayout.addWidget(self.hotkey)
        self.buttonBox = QtWidgets.QDialogButtonBox(Configuration)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Configuration)
        QtCore.QMetaObject.connectSlotsByName(Configuration)

    def retranslateUi(self, Configuration):
        _translate = QtCore.QCoreApplication.translate
        Configuration.setWindowTitle(_translate("Configuration", "Dialog"))
        self.label.setText(_translate("Configuration", "Audio Device"))
        self.label_2.setText(_translate("Configuration", "Hot Key"))
from muter.ui import micmuter_rc
