# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'config.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.WindowModal)
        Form.resize(371, 162)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/icon-light.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setLayoutDirection(QtCore.Qt.LeftToRight)
        Form.setAutoFillBackground(False)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.audio = QtWidgets.QWidget(Form)
        self.audio.setObjectName("audio")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.audio)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.audio)
        self.label.setMinimumSize(QtCore.QSize(128, 0))
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.audioCombo = QtWidgets.QComboBox(self.audio)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.audioCombo.sizePolicy().hasHeightForWidth())
        self.audioCombo.setSizePolicy(sizePolicy)
        self.audioCombo.setObjectName("audioCombo")
        self.horizontalLayout.addWidget(self.audioCombo)
        self.verticalLayout.addWidget(self.audio)
        self.hotkey = QtWidgets.QWidget(Form)
        self.hotkey.setObjectName("hotkey")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.hotkey)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.hotkey)
        self.label_2.setMinimumSize(QtCore.QSize(128, 0))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.hotkeyCombo = QtWidgets.QComboBox(self.hotkey)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hotkeyCombo.sizePolicy().hasHeightForWidth())
        self.hotkeyCombo.setSizePolicy(sizePolicy)
        self.hotkeyCombo.setObjectName("hotkeyCombo")
        self.horizontalLayout_2.addWidget(self.hotkeyCombo)
        self.verticalLayout.addWidget(self.hotkey)
        self.buttons = QtWidgets.QDialogButtonBox(Form)
        self.buttons.setAutoFillBackground(False)
        self.buttons.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Save)
        self.buttons.setCenterButtons(False)
        self.buttons.setObjectName("buttons")
        self.verticalLayout.addWidget(self.buttons)

        self.retranslateUi(Form)
        self.buttons.accepted.connect(Form.accepted)
        self.buttons.rejected.connect(Form.rejected)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Configuration"))
        self.label.setText(_translate("Form", "Audio Device"))
        self.label_2.setText(_translate("Form", "Hot Key"))
from muter.ui import micmuter_rc
