# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'config.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Configuration(object):
    def setupUi(self, Configuration):
        Configuration.setObjectName("Configuration")
        Configuration.setWindowModality(QtCore.Qt.ApplicationModal)
        Configuration.resize(174, 89)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Configuration.sizePolicy().hasHeightForWidth())
        Configuration.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/icon-light.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Configuration.setWindowIcon(icon)
        Configuration.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.verticalLayout = QtWidgets.QVBoxLayout(Configuration)
        self.verticalLayout.setObjectName("verticalLayout")
        self.hotkey = QtWidgets.QWidget(Configuration)
        self.hotkey.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.hotkey.setObjectName("hotkey")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.hotkey)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.hotkey)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.hotKey = QtWidgets.QLineEdit(self.hotkey)
        self.hotKey.setFrame(True)
        self.hotKey.setAlignment(QtCore.Qt.AlignCenter)
        self.hotKey.setReadOnly(True)
        self.hotKey.setObjectName("hotKey")
        self.horizontalLayout_2.addWidget(self.hotKey)
        self.verticalLayout.addWidget(self.hotkey)
        self.buttonBox = QtWidgets.QDialogButtonBox(Configuration)
        self.buttonBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Configuration)
        QtCore.QMetaObject.connectSlotsByName(Configuration)

    def retranslateUi(self, Configuration):
        _translate = QtCore.QCoreApplication.translate
        Configuration.setWindowTitle(_translate("Configuration", "Configuration"))
        self.label.setText(_translate("Configuration", "Hotkey"))
        self.hotKey.setPlaceholderText(_translate("Configuration", "Press a key to assign the hot key"))
from muter.ui import micmuter_rc
