# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'micmuter.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(296, 62)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(mainWindow.sizePolicy().hasHeightForWidth())
        mainWindow.setSizePolicy(sizePolicy)
        mainWindow.setMaximumSize(QtCore.QSize(320, 200))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/icon-light.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        mainWindow.setWindowIcon(icon)
        mainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.hkey_frame = QtWidgets.QWidget(self.centralwidget)
        self.hkey_frame.setObjectName("hkey_frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.hkey_frame)
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.setHotkeyButton = QtWidgets.QPushButton(self.hkey_frame)
        self.setHotkeyButton.setObjectName("setHotkeyButton")
        self.horizontalLayout_2.addWidget(self.setHotkeyButton)
        self.hotKey = QtWidgets.QLineEdit(self.hkey_frame)
        self.hotKey.setMinimumSize(QtCore.QSize(197, 0))
        self.hotKey.setFrame(True)
        self.hotKey.setAlignment(QtCore.Qt.AlignCenter)
        self.hotKey.setReadOnly(True)
        self.hotKey.setObjectName("hotKey")
        self.horizontalLayout_2.addWidget(self.hotKey)
        self.verticalLayout.addWidget(self.hkey_frame)
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 296, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        mainWindow.setMenuBar(self.menubar)
        self.actionQuit = QtWidgets.QAction(mainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionMinimizeToTray = QtWidgets.QAction(mainWindow)
        self.actionMinimizeToTray.setObjectName("actionMinimizeToTray")
        self.menuFile.addAction(self.actionMinimizeToTray)
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Mic Muter"))
        self.setHotkeyButton.setText(_translate("mainWindow", "Set Hotkey"))
        self.hotKey.setPlaceholderText(_translate("mainWindow", "Press a key to assign the hot key"))
        self.menuFile.setTitle(_translate("mainWindow", "File"))
        self.actionQuit.setText(_translate("mainWindow", "Quit"))
        self.actionMinimizeToTray.setText(_translate("mainWindow", "Minimize"))
from muter.ui import micmuter_rc
